
DROP TABLE PERSONNE

CREATE TABLE PERSONNE
(
	[Id] INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	[Firstname] VARCHAR(50) NOT NULL,
	[Lastname] VARCHAR(50) NOT NULL,
	[DateOfBirth] DATETIME NOT NULL
)


DROP TABLE ADRESSE

CREATE TABLE ADRESSE
(
	[Id] INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	[Numero] INT NOT NULL,
	[Rue] VARCHAR(50) NOT NULL,
	[CodePostal] INT NOT NULL,
	[Ville] VARCHAR(50) NOT NULL,
	[Pays] VARCHAR(50) NOT NULL
)

DROP TABLE CONTACT

CREATE TABLE CONTACT
(
	[Id] INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	[Email] VARCHAR(50) NOT NULL,
	[Telephone] VARCHAR (17) NOT NULL
)
