DROP TABLE PERSON;
DROP TABLE CONTACT;
DROP TABLE ADDRESS;

CREATE TABLE PERSON
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOM VARCHAR(50) NOT NULL,
	PRENOM VARCHAR(50) NOT NULL,
	DATE_NAISSANCE DATETIME NOT NULL
)


INSERT INTO [dbo].[PERSON] ( [NOM], [PRENOM], [DATE_NAISSANCE]) 
VALUES ( N'Anthony', N'Di Persio', N'1990-06-20 00:00:00'),
	   ( N'Ihab', N'Abadi', N'1987-09-11 00:00:00'),
	   ( N'Marine', N'Abadi', N'1992-05-16 00:00:00')


CREATE TABLE CONTACT
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EMAIL VARCHAR(50) NOT NULL,
	TELEPHONE VARCHAR(50) NOT NULL,
	PERSON_ID INT NOT NULL,
	ADDRESS_ID INT NOT NULL,
)


INSERT INTO [dbo].[CONTACT] ( [EMAIL], [TELEPHONE], [PERSON_ID], [ADDRESS_ID])
VALUES ( N'anthony@utopios.net', N'+3 6 41 52 63 98', 1, 1),
	   ( N'Ihab@utopios.net', N'+33 6 58 74 12 36', 2, 2),
	   ( N'marine@utopios.net', N'+33 6 41 02 10 02', 3, 3)


CREATE TABLE ADDRESS
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NUMBER INT NOT NULL,
	ROAD_NAME VARCHAR(50) NOT NULL,
	POSTAL_CODE INT NOT NULL,
	TOWN VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
)


INSERT INTO [dbo].[ADDRESS] ( [NUMBER], [ROAD_NAME], [POSTAL_CODE], [TOWN], [COUNTRY]) 
VALUES ( 11, N'rue de la République', 59780, N'Willems', N'France'),
	   ( 2, N'rue des Tilleuls', 59599, N'Tourcoing', N'France'),
	   ( 2, N'rue des Tilleuls', 59599, N'Tourcoing', N'France')


